# docker-compose.yml
version: "3"
services:
  app:
    image: 127.0.0.1:5000/app
    build:
      context: .
      dockerfile: ./docker/dockerfile
    depends_on:
      - postgres
    environment:
      DB_CONN: postgres://user:pass@postgres:5432/todo-list
      PORT: 1234
    ports:
      - "1234:1234"
    volumes:
      - ./app:/app
      - /app/node_modules
  postgres:
    image: postgres:10.4
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: todo-list
